export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const INVOICE_REPOSITORY = 'INVOICE_REPOSITORY';
export const DB_NAME = 'AlphaDiceDb';
export const CRON_INVOICE_NOTIFICATIONS = '45 * * * * *';


export const enum SceneNames {
  ADD_INVOICE = 'ADD_INVOICE',
  ADD_ORDER = "ADD_ORDER",
  DECLARE_PAYMENT = "DECLARE_PAYMENT",
  ADD_PROJECT = "ADD_PROJECT",
  ADD_INVOICE_DETAILS = "ADD_INVOICE_DETAILS",
  CONFIRM_PAYMENT = "CONFIRM_PAYMENT"
}